# Generated by Django 5.1 on 2024-08-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie_list',
            name='desc',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='title',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
